#pragma once

#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\Actor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\Asset.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\CameraActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\CameraComponent.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\CubeMeshActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\CustomMeshActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\LightActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\LightComponent.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\MaterialAsset.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\MeshActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\MeshRenderComponent.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\MeshVertexComponent.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\SphereMeshActor.reflection.cpp"
#include "G:/Toy/ZeroEngine/ZeroEngine\Intermediate\TransformComponent.reflection.cpp"