#pragma once

#define GENERATED_BODY_INNER(A,B,C,D) A##B##C##D
#define GENERATED_BODY_MACRO(A,B,C,D) GENERATED_BODY_INNER(A, B, C, D)

#define UENUM(...)
#define UCLASS(...)
#define UPROPERTY(...)
#define UFUNCTION(...)
#define USTRUCT(...)

#define GENERATED_BODY(...) GENERATED_BODY_MACRO(REFLECTION_FILE_NAME, _, TAG_LINE, _GENERATED_BODY)
